discovery:
  password: ${EUREKA_PASSWORD:unc2020pass}
  user: ${EUREKA_UID:unc2020}
  host: ${EUREKA_HOST:localhost:8761}
  protocol: ${EUREKA_PROTOCOL:http}
  url: ${discovery.protocol}://${discovery.user}:${discovery.password}@${discovery.host}/eureka
config:
  password: ${CFG_PASSWORD:unc2020pass}
  user: ${CFG_UID:unc2020}
  host: ${CFG_HOST:localhost:8762}
  protocol: ${CFG_PROTOCOL:http}
  url: ${config.protocol}://${config.user}:${config.password}@${config.host}/
spring:
  application:
    name: configserver
  main:
    banner-mode: off
  security:
    user:
      password: ${config.password}
      name: ${config.user}
  cloud:
    config:
      server:
        native:
          search-locations: [classpath:/config, file:./config, file:../config_repo]
server:
  port: ${PORT:8762}
eureka:
  client:
    service-url:
      defaultZone: ${discovery.url}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15
logging:
  level:
    org.springframework.cloud: debug
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
---
spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL:file://config_repo}
          ignoreLocalSshSettings: true
          skipSslValidation: true
          privateKey: |
            ${DEPLOY_KEY:test}
          basedir: target/repo
          force-pull: true
          preferredAuthentications: publickey
  config:
    activate:
      on-profile: git
