- label: "Setup"
  message: "Completed"
  color: "green"
- label: "PR Size"
  message: "Large"
  color: "red"
  when: "$additions > 20"
- label: "PR Size"
  message: "Medium"
  color: "yellow"
  when: "$additions > 6 && $additions < 20"
- label: "PR Size"
  message: "Small"
  color: "greed"
  when: "$additions < 6"