version = 1

test_patterns = ["test/**"]

exclude_patterns = ["**/target/**"]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"

[[transformers]]
name = "prettier"
enabled = true
