version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    steps:
      - checkout
      - run:
          name: Run build
          command: mvn -T 2C package

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud