spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    platform: h2
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
---
server:
  port: ${PORT:8088}
spring:
  application:
    name: gibdd
  config:
    activate:
      on-profile: gibdd

