spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    platform: h2
server:
  port: ${PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
