- uses: nashmaniac/create-issue-action@v1.1
  name: Create Issue Action
  with:
    title: Build Failed
    token: ${{secrets.GITHUB_TOKEN}}
    assignees: ${{github.actor}}
    labels: worflow-failed
    body: Workflow failed for commit ${{github.sha}}