# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build project with Maven

on:
  push:
    branches: [ nikita, artem, develop, "feature/*" ]
  pull_request:
    branches: [ nikita, artem, develop, "feature/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Load Code
      uses: actions/checkout@v2
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -T 2C -B package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar --file pom.xml
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: BUILD
        path: ./**/target/*.jar
