on:
  push:
    branches: [ nikita, artem, develop ]
  pull_request:
    branches: [ nikita, artem, develop ]
name: Find Secrets
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove README.MD
        uses: JesseTG/rm@v1.0.2
        with:
          path: README.MD
      - uses: max/secret-scan@master