on:
  push:
    branches: [ nikita, artem, develop ]
  pull_request:
    branches: [ nikita, artem, develop ]
name: Find Secrets
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master